import { useEffect, useMemo, useRef, useState } from 'react'
import { build, getArtifacts, getExample, getJob, validate as validateBackend } from './api/client'
import { BladeViewer } from './components/BladeViewer'
import { DistributionTable } from './components/DistributionTable'
import { NumericInput } from './components/NumericInput'
import { addAirfoilStation, canonicalJson, changeRootRadius, coordinateNacaThickness, effectiveThickness, parseBladeSpec, removeAirfoilStation, setThicknessOverride, validateEditorSpec } from './editor/bladespecEditor'
import type { AirfoilSection, Artifact, BladeSpec, Distribution, Job } from './types/bladespec'
import './styles.css'
import './sprint02.css'

const curves:[keyof BladeSpec,string,string][]=[['chord_distribution','Chord','chord_over_R'],['twist_distribution','Twist','twist_deg'],['rake_distribution','Rake','rake_over_R'],['skew_distribution','Skew','skew_over_R'],['thickness_distribution','Thickness','thickness_ratio']]
type StationResult={requested_r_over_R:number;sampled_r_over_R:number;station_roles:string[];chord_absolute_error_mm:number;twist_absolute_error_deg:number;reference_axis_position_error_mm:number;te_absolute_error_mm:number;contour_rms_mm:number;contour_p95_mm:number;contour_max_mm:number}
type ValidationResult={solidification:{solid_after_reimport:{solids:number;closed_shell:boolean;brepcheck_valid:boolean;free_edges:number;volume_mm3:number;volume_method:string};roundtrip:{one_solid:boolean;volume_delta_mm3:number}};geometry_validation?:{passed:boolean;max_chord_error_mm:number;max_twist_error_deg:number;max_reference_axis_error_mm:number;max_te_error_mm:number;control_contour_rms_max_mm:number;control_contour_p95_max_mm:number;control_contour_max_mm:number;root_measurement:{requested_r_over_R:number;measured_r_over_R:number};tip_measurement:{requested_r_over_R:number;measured_r_over_R:number};stations:StationResult[]}}
const newIds=(count:number)=>Array.from({length:count},()=>crypto.randomUUID())

export default function App(){
  const [spec,setSpec]=useState<BladeSpec>(); const [baseline,setBaseline]=useState<BladeSpec>(); const [rowIds,setRowIds]=useState<string[]>([]); const [epoch,setEpoch]=useState(0)
  const [message,setMessage]=useState('Loading example…'); const [errors,setErrors]=useState<string[]>([]); const [job,setJob]=useState<Job>(); const [artifacts,setArtifacts]=useState<Artifact[]>([]); const [validationResult,setValidationResult]=useState<ValidationResult>(); const [resultSnapshot,setResultSnapshot]=useState<string>(); const [submittedSnapshot,setSubmittedSnapshot]=useState<string>();
  const activeJob=useRef<string | undefined>(undefined); const fileInput=useRef<HTMLInputElement>(null)
  const load=(next:BladeSpec,remember=false)=>{setSpec(structuredClone(next));setRowIds(newIds(next.airfoil_sections.length));setEpoch(v=>v+1);setErrors([]);setMessage('BladeSpec loaded');if(remember)setBaseline(structuredClone(next))}
  useEffect(()=>{getExample().then(s=>load(s,true)).catch(e=>setMessage(String(e)))},[])
  useEffect(()=>{if(!job||!['queued','running'].includes(job.status))return;const id=job.job_id;const timer=window.setTimeout(()=>getJob(id).then(next=>{if(activeJob.current===id)setJob(next)}).catch(e=>setMessage(String(e))),750);return()=>clearTimeout(timer)},[job])
  useEffect(()=>{if(job?.status!=='succeeded'||activeJob.current!==job.job_id)return;const id=job.job_id;getArtifacts(id).then(async items=>{if(activeJob.current!==id)return;const validation=items.find(item=>item.name==='validation.json');const result=validation?await fetch(validation.download_url).then(r=>r.json()) as ValidationResult:undefined;if(activeJob.current!==id)return;setArtifacts(items);setValidationResult(result);setResultSnapshot(submittedSnapshot);setMessage('Build, topology, and independent geometry validation passed')}).catch(e=>setMessage(String(e)))},[job,submittedSnapshot])
  const revision=useMemo(()=>spec?canonicalJson(spec):'', [spec]); const stale=Boolean(resultSnapshot&&resultSnapshot!==revision); const busy=job?.status==='queued'||job?.status==='running'
  if(!spec)return <main><h1>BladeGen</h1><p>{message}</p></main>
  const update=(next:BladeSpec)=>{setSpec(next);setErrors(validateEditorSpec(next))}
  const field=<K extends keyof BladeSpec>(key:K,value:BladeSpec[K])=>update({...spec,[key]:value})
  const updateSection=(index:number,change:Partial<AirfoilSection>)=>update({...spec,airfoil_sections:spec.airfoil_sections.map((s,i)=>i===index?{...s,...change}:s)})
  const changeStationRadius=(index:number,radius:number)=>{if(index===0||index===spec.airfoil_sections.length-1)throw new Error('Root and tip radii are controlled by the global domain');const before=spec.airfoil_sections[index-1].r_over_R,after=spec.airfoil_sections[index+1].r_over_R;if(radius<=before||radius>=after)throw new Error(`Radius must be between ${before} and ${after}`);let next={...spec,airfoil_sections:spec.airfoil_sections.map((s,i)=>i===index?{...s,r_over_R:radius}:s)};const section=next.airfoil_sections[index];if(section.airfoil.type==='naca4'&&section.thickness_override_ratio===undefined)next=coordinateNacaThickness(next,index,section.airfoil.code);update(next)}
  const addStation=()=>{try{let gap=-1,radius=0;for(let i=0;i<spec.airfoil_sections.length-1;i++){const candidate=spec.airfoil_sections[i+1].r_over_R-spec.airfoil_sections[i].r_over_R;if(candidate>gap){gap=candidate;radius=(spec.airfoil_sections[i+1].r_over_R+spec.airfoil_sections[i].r_over_R)/2}}const next=addAirfoilStation(spec,radius);const insertion=next.airfoil_sections.findIndex(s=>s.r_over_R===radius);setRowIds(ids=>[...ids.slice(0,insertion),crypto.randomUUID(),...ids.slice(insertion)]);update(next);setMessage(`Inserted airfoil station at r/R=${radius}`)}catch(e){setErrors([e instanceof Error?e.message:String(e)])}}
  const removeStation=(index:number)=>{try{update(removeAirfoilStation(spec,index));setRowIds(ids=>ids.filter((_,i)=>i!==index))}catch(e){setErrors([e instanceof Error?e.message:String(e)])}}
  const changeNaca=(index:number,code:string)=>update(coordinateNacaThickness(spec,index,code))
  const toggleOverride=(index:number,enabled:boolean)=>{const section=spec.airfoil_sections[index];if(enabled)update(setThicknessOverride(spec,index,effectiveThickness(spec,section)));else{const {thickness_override_ratio:_,...without}=section;let next={...spec,airfoil_sections:spec.airfoil_sections.map((s,i)=>i===index?without:s)};if(without.airfoil.type==='naca4')next=coordinateNacaThickness(next,index,without.airfoil.code);update(next)}}
  const submit=async()=>{const local=validateEditorSpec(spec);setErrors(local);if(local.length){setMessage('Correct input errors before generation');return}try{setMessage('Validating BladeSpec…');await validateBackend(spec);const snapshot=canonicalJson(structuredClone(spec));setSubmittedSnapshot(snapshot);setMessage('Submitting real CAD build…');const next=await build(spec);activeJob.current=next.job_id;setJob(next)}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
  const check=async()=>{const local=validateEditorSpec(spec);setErrors(local);if(local.length){setMessage('Input validation failed');return}try{await validateBackend(spec);setMessage('Input validation passed')}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
  const exportJson=()=>{const blob=new Blob([JSON.stringify(spec,null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${spec.name||'blade'}.json`;a.click();URL.revokeObjectURL(url)}
  const importJson=async(file?:File)=>{if(!file)return;try{load(parseBladeSpec(await file.text()));setMessage(`Opened ${file.name}`)}catch(e){setErrors([e instanceof Error?e.message:String(e)])}}
  const reset=()=>{if(baseline&&window.confirm('Discard current edits and reload the example?'))load(baseline)}
  const createNew=()=>{if(window.confirm('Start a new blade from neutral defaults?'))load({...structuredClone(baseline??spec),name:'untitled_blade'})}
  const preview=artifacts.find(a=>a.name==='blade_preview.stl'); const solid=validationResult?.solidification.solid_after_reimport; const geometry=validationResult?.geometry_validation
  return <main><header><div><p className="eyebrow">LEVEL 1 · SPRINT 02</p><h1>BladeGen</h1><p>BladeSpec → OpenVSP → independently validated OCP solid</p></div><div className="actions"><button onClick={createNew}>New</button><button onClick={()=>fileInput.current?.click()}>Open JSON</button><input ref={fileInput} hidden type="file" accept="application/json,.json" onChange={e=>importJson(e.target.files?.[0])}/><button onClick={exportJson}>Export JSON</button><button onClick={()=>baseline&&load(baseline)}>Load Example</button><button onClick={reset}>Reset</button><button onClick={check}>Validate</button><button className="primary" disabled={busy} onClick={submit}>{busy?'Generating…':'Generate Blade'}</button></div></header>
    <div className={`status ${stale?'stale':''}`}><strong>{job?`Job ${job.job_id.slice(0,8)} · ${job.status}`:'Editor'}</strong> — {message}{stale&&<b> · Inputs changed — regenerate to update CAD.</b>}{job?.error&&<span className="error"> — {job.error}</span>}</div>{errors.length>0&&<div className="error-panel"><strong>Input validation</strong><ul>{errors.map(error=><li key={error}>{error}</li>)}</ul></div>}
    <div className="layout"><div className="editor"><section><h2>Global settings</h2><div className="grid"><label>Name<input value={spec.name} onChange={e=>field('name',e.target.value)}/></label><label>Diameter (mm)<NumericInput label="Diameter" value={spec.diameter_mm} onCommit={v=>field('diameter_mm',v)}/></label><label>Root r/R<NumericInput label="Root radius" step=".01" value={spec.root_radius_ratio} onCommit={v=>update(changeRootRadius(spec,v))}/></label><label>Reference x/c<NumericInput label="Reference axis" step=".01" value={spec.reference_axis_x_over_c} onCommit={v=>field('reference_axis_x_over_c',v)}/></label><label>Rotation<select value={spec.rotation_direction} onChange={e=>field('rotation_direction',e.target.value as 'normal'|'reverse')}><option value="normal">Normal</option><option value="reverse">Reverse</option></select></label></div></section>
    <section><div className="section-title"><h2>Airfoil Stations ({spec.airfoil_sections.length})</h2><button onClick={addStation}>Add Airfoil Station</button></div><table><thead><tr><th>r/R</th><th>Profile</th><th>TE mm</th><th>Effective t/c</th><th>Override</th><th/></tr></thead><tbody>{spec.airfoil_sections.map((s,i)=><tr key={rowIds[i]}><td><NumericInput label={`Airfoil radius ${i+1}`} step=".01" value={s.r_over_R} disabled={i===0||i===spec.airfoil_sections.length-1} onCommit={v=>changeStationRadius(i,v)}/></td><td>{s.airfoil.type==='naca4'?<input aria-label={`NACA code ${i+1}`} inputMode="numeric" maxLength={4} value={s.airfoil.code} onChange={e=>changeNaca(i,e.target.value)}/>:<details><summary>Coordinate profile</summary><pre>{JSON.stringify(s.airfoil,null,2)}</pre></details>}</td><td><NumericInput label={`TE thickness ${i+1}`} step=".1" value={s.trailing_edge_thickness_mm} onCommit={v=>updateSection(i,{trailing_edge_thickness_mm:v})}/></td><td>{effectiveThickness(spec,s).toFixed(4)}</td><td><label className="inline"><input type="checkbox" checked={s.thickness_override_ratio!==undefined} onChange={e=>toggleOverride(i,e.target.checked)}/> explicit</label>{s.thickness_override_ratio!==undefined&&<NumericInput label={`Thickness override ${i+1}`} step=".01" value={s.thickness_override_ratio} onCommit={v=>update(setThicknessOverride(spec,i,v))}/>}</td><td><button disabled={i===0||i===spec.airfoil_sections.length-1} onClick={()=>removeStation(i)}>Remove</button></td></tr>)}</tbody></table><p className="hint">Airfoil and curve grids remain independent. New NACA stations receive an explicit thickness control only when needed for consistency.</p></section>
    <section><h2>Independent Spanwise Distributions</h2><div className="curves">{curves.map(([key,title,valueKey])=><DistributionTable key={`${String(key)}-${epoch}`} title={title} valueKey={valueKey} value={spec[key] as Distribution} onChange={v=>field(key,v as BladeSpec[typeof key])} onError={e=>setErrors(e?[e]:[])}/>)}</div></section></div>
    <aside><h2>Solid preview</h2>{preview&&<p className={stale?'preview-label stale':'preview-label'}>Preview from job {job?.job_id.slice(0,8)}{stale?' · previous inputs':''}</p>}<BladeViewer url={preview?.download_url}/>{solid&&<><h2>STEP topology</h2><dl><dt>Solid / free edges</dt><dd>{solid.solids} / {solid.free_edges}</dd><dt>Closed / BRep valid</dt><dd>{String(solid.closed_shell)} / {String(solid.brepcheck_valid)}</dd><dt>Adaptive volume</dt><dd>{solid.volume_mm3.toFixed(6)} mm³</dd></dl></>}{geometry&&<><h2>Independent geometry</h2><dl><dt>Overall</dt><dd>{geometry.passed?'PASS':'FAIL'}</dd><dt>Chord / twist max</dt><dd>{geometry.max_chord_error_mm.toFixed(5)} mm / {geometry.max_twist_error_deg.toFixed(5)}°</dd><dt>Axis / TE max</dt><dd>{geometry.max_reference_axis_error_mm.toFixed(5)} / {geometry.max_te_error_mm.toFixed(5)} mm</dd><dt>Contour RMS / P95 / max</dt><dd>{geometry.control_contour_rms_max_mm.toFixed(5)} / {geometry.control_contour_p95_max_mm.toFixed(5)} / {geometry.control_contour_max_mm.toFixed(5)} mm</dd><dt>Root requested / sampled</dt><dd>{geometry.root_measurement.requested_r_over_R} / {geometry.root_measurement.measured_r_over_R}</dd><dt>Tip requested / sampled</dt><dd>{geometry.tip_measurement.requested_r_over_R} / {geometry.tip_measurement.measured_r_over_R}</dd></dl><details><summary>Per-station measurements ({geometry.stations.length})</summary><table><thead><tr><th>Requested</th><th>Sampled</th><th>Roles</th><th>Chord</th><th>Twist</th><th>TE</th></tr></thead><tbody>{geometry.stations.map(row=><tr key={row.requested_r_over_R}><td>{row.requested_r_over_R}</td><td>{row.sampled_r_over_R}</td><td>{row.station_roles.join(', ')}</td><td>{row.chord_absolute_error_mm.toFixed(4)}</td><td>{row.twist_absolute_error_deg.toFixed(4)}</td><td>{row.te_absolute_error_mm.toFixed(4)}</td></tr>)}</tbody></table></details></>}<h2>Artifacts</h2>{artifacts.length?<ul>{artifacts.map(a=><li key={a.name}><a href={a.download_url}>{a.name}</a> <small>{Math.ceil(a.size_bytes/1024)} KB</small></li>)}</ul>:<p>No completed build artifacts yet.</p>}</aside></div>
  </main>
}
